### ISSUE TITLE
scrolling glitch that only happens with ur hide nitro upselling theme (vesktop 1.5.3)

### ISSUE THREAD

**Issue by comfortablemilk4454** [D3SOX/complementary-discord-theme#6]
hi! first of all, love your hide nitro upselling theme! ive noticed, however, a scrolling glitch on the dm list that only happens with the https://d3sox.me/complementary-discord-theme/hide-nitro-upselling.theme.css online theme on [vesktop 1.5.3](https://github.com/Vencord/Vesktop/releases/tag/v1.5.3) (& also on vencord). see the screen recording to see the glitch happening. thanks so much!

https://github.com/D3SOX/complementary-discord-theme/assets/43555540/3d42fdb7-e6d1-4d2b-b8ef-f1f717a5cbbd

**Comment by D3SOX** [comment]
I don't get how it glitches?

**Comment by comfortablemilk4454** [comment]
see at 4 seconds. as i scroll down there becomes a grey space under the last dm on the dm list, and then immediately after it snaps back to just displaying the dm list (without the grey space)

**Comment by D3SOX** [comment]
Ah I see you mean the empty space on the left causes it to scroll down by the space on the right:
![image](https://github.com/D3SOX/complementary-discord-theme/assets/24937357/87a62584-4e77-41e8-9ffe-88fe8dbf2684)

Does this also happen to you when disable all other Themes/QuickCSS? Because I can't reproduce this. I'm also using Vesktop but on Linux instead of macOS

**Comment by comfortablemilk4454** [comment]
it does. i think its a macOS thing.

**Comment by comfortablemilk4454** [comment]
@D3SOX bump

**Comment by D3SOX** [comment]
I can't reproduce this so there's nothing I can do about it now

**Comment by comfortablemilk4454** [comment]
rip, all good.
